skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
riff = "59MehWKuM1t6u3LAD4nyEg3kBw1HKq5EbS4ByKsosqtV"
riff_dbc = "gATYd3vfHCPCrhFupj8HxVX78syyXNfPSbYRsttm9RF"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
