# Always build for SBPF v0: it deploys on every cluster and runs in LiteSVM's
# default runtime. (Anchor 1.x defaults to v3, which LiteSVM rejects.)
ARCH ?= v0

.PHONY: build build-devnet test fmt lint clean deploy-devnet deploy-passport-devnet idl vectors

# The programs only. Their interface (IDL) is generated by `make idl`, which
# compiles everything a second time with Anchor's idl-build feature, so
# everyday builds skip it.
build:
	anchor build --arch $(ARCH) --no-idl

# Publish the program's interface (IDL + TypeScript types) in idl/, so
# clients can use it without building Rust. CI fails if it's stale.
idl:
	mkdir -p idl
	anchor idl build -p riff -o idl/riff.json -t idl/riff.ts
	anchor idl build -p riff_passport -o idl/riff_passport.json -t idl/riff_passport.ts
	rm -f idl/*_errors.ts  # also written by Anchor's --out-ts; not part of the published interface

# Regenerate vectors/curve.json from the program's curve math.
vectors:
	cargo test -p riff --test all curve_vectors -- --ignored

# Devnet build of riff (Raydium's devnet addresses), saved as riff-devnet.so
# so it can't be mistaken for the mainnet riff.so. Only riff has devnet
# differences. It builds in its own target directory, so the mainnet build
# (which the tests use) is never switched to devnet and back.
build-devnet:
	CARGO_TARGET_DIR=$(CURDIR)/target/devnet cargo build-sbf --manifest-path programs/riff/Cargo.toml \
	  --arch $(ARCH) --features devnet --sbf-out-dir $(CURDIR)/target/devnet/deploy
	cp target/devnet/deploy/riff.so target/deploy/riff-devnet.so

test: build
	cargo test

fmt:
	cargo fmt --all

lint:
	cargo clippy --all-targets -- -D warnings

clean:
	anchor clean

# Devnet deployment (keys in ~/.config/riff/devnet, never in the repo).
DEVNET_KEYS ?= $(HOME)/.config/riff/devnet

deploy-devnet: build-devnet
	solana program deploy target/deploy/riff-devnet.so \
	  --program-id target/deploy/riff-keypair.json \
	  --keypair $(DEVNET_KEYS)/deployer.json --url devnet

deploy-passport-devnet: build
	solana program deploy target/deploy/riff_passport.so \
	  --program-id target/deploy/riff_passport-keypair.json \
	  --keypair $(DEVNET_KEYS)/deployer.json --url devnet

