//! Generates test vectors for the TypeScript client's port of the curve math
//! (clients/ts/src/curve.ts), from the program's own Rust code.
//!
//! Regenerate with:
//!   cargo test -p riff --test curve_vectors -- --ignored
//! CI checks the committed file is up to date.

use {
    riff::curve::{graduation_virtual_token_reserves, quote_buy, quote_sell, split_fee, Reserves},
    serde_json::{json, Value},
};

const SOL: u64 = 1_000_000_000;
const TOKEN: u64 = 1_000_000;
const SUPPLY: u64 = 1_000_000_000 * TOKEN;
const CURVE: u64 = 793_100_000 * TOKEN;
const OUT: &str = concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../clients/ts/test/curve-vectors.json"
);

struct Lcg(u64);
impl Lcg {
    fn next(&mut self) -> u64 {
        self.0 = self
            .0
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        self.0 >> 11
    }
    fn below(&mut self, n: u64) -> u64 {
        if n == 0 {
            0
        } else {
            self.next() % n
        }
    }
}

fn reserves_json(r: &Reserves) -> Value {
    json!({
        "virtualSol": r.virtual_sol.to_string(),
        "virtualToken": r.virtual_token.to_string(),
        "realToken": r.real_token.to_string(),
        "realSol": r.real_sol.to_string(),
    })
}

/// Curves seen in practice: fresh mainnet (30 SOL) and devnet (0.3 SOL),
/// then random points along each after a series of buys and sells.
fn curves(rng: &mut Lcg) -> Vec<Reserves> {
    let vt0 = graduation_virtual_token_reserves(SUPPLY, CURVE).unwrap();
    let mut out = vec![];
    for vs0 in [30 * SOL, 3 * SOL / 10] {
        let mut r = Reserves {
            virtual_sol: vs0,
            virtual_token: vt0,
            real_token: CURVE,
            real_sol: 0,
        };
        out.push(r);
        for _ in 0..40 {
            if rng.below(3) > 0 {
                if let Some(q) = quote_buy(&r, 100, 1 + rng.below(vs0 / 4)) {
                    r = r.apply_buy(&q).unwrap();
                }
            } else {
                let held = CURVE - r.real_token;
                let tokens_in = 1 + rng.below(held.max(1));
                if let Some(q) = quote_sell(&r, 100, tokens_in) {
                    r = r.apply_sell(tokens_in, &q).unwrap();
                }
            }
            out.push(r);
        }
    }
    out
}

#[test]
#[ignore = "writes clients/ts/test/curve-vectors.json; run explicitly"]
fn generate_curve_vectors() {
    let mut rng = Lcg(0x72_69_66_66);
    let fee_rates = [0u16, 1, 30, 100, 333, 1_000];
    let mut buys = vec![];
    let mut sells = vec![];
    for r in curves(&mut rng) {
        let scale = r.virtual_sol;
        for &fee_bps in &fee_rates {
            // Dust, typical, and far more than the curve holds (final buy).
            let amounts = [
                1,
                2,
                99,
                101,
                1 + rng.below(1_000_000),
                1 + rng.below(scale),
                1 + rng.below(scale * 4),
                scale * 1_000,
            ];
            for max_sol_in in amounts {
                let q = quote_buy(&r, fee_bps, max_sol_in).map(|q| json!({
                    "tokensOut": q.tokens_out.to_string(), "solToCurve": q.sol_to_curve.to_string(),
                    "fee": q.fee.to_string(), "totalCost": q.total_cost.to_string(),
                }));
                buys.push(json!({ "reserves": reserves_json(&r), "feeBps": fee_bps, "maxSolIn": max_sol_in.to_string(), "quote": q }));
            }
            let held = (CURVE - r.real_token).max(1);
            for tokens_in in [1, 35_000, 1 + rng.below(held), held, held * 3] {
                let q = quote_sell(&r, fee_bps, tokens_in).map(|q| json!({
                    "solFromCurve": q.sol_from_curve.to_string(), "fee": q.fee.to_string(), "solOut": q.sol_out.to_string(),
                }));
                sells.push(json!({ "reserves": reserves_json(&r), "feeBps": fee_bps, "tokensIn": tokens_in.to_string(), "quote": q }));
            }
        }
    }
    let mut splits = vec![];
    for (a, c, p) in [
        (50u16, 20u16, 30u16),
        (0, 0, 0),
        (1, 1, 1),
        (500, 300, 200),
        (100, 0, 0),
        (0, 0, 100),
    ] {
        for fee in [
            0u64,
            1,
            2,
            3,
            7,
            99,
            100,
            101,
            12_345_677,
            10_000_000,
            1 + rng.below(u32::MAX as u64),
        ] {
            let s = split_fee(fee, a, c, p);
            splits.push(json!({ "fee": fee.to_string(), "bps": [a, c, p],
                "split": { "artist": s.artist.to_string(), "creator": s.creator.to_string(), "protocol": s.protocol.to_string() } }));
        }
    }
    let file = json!({
        "_about": "Generated by programs/riff/tests/curve_vectors.rs from the program's curve code. Do not edit.",
        "buys": buys, "sells": sells, "splits": splits,
    });
    std::fs::write(OUT, serde_json::to_string(&file).unwrap() + "\n").unwrap();
    println!(
        "wrote {} buys, {} sells, {} splits",
        buys.len(),
        sells.len(),
        splits.len()
    );
}
